<div class="field phone_number">
    <label class="label" for="phone_number">
        <span><?= $block->escapeHtml(__('Phone number')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="phone_number" id="phone_number" value="" title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>" class="input-text">
    </div>
</div>

<div class="field tenant_name">
    <label class="label" for="tenant_name">
        <span><?= $block->escapeHtml(__('Tenant name')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="tenant_name" id="phone_number" value="" title="<?= $block->escapeHtmlAttr(__('Tenant name')) ?>" class="input-text">
    </div>
</div>
