

<?php

/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */


// var_dump($block->_prepareLayout());

?>



<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<br>

<br>
<div class="block block-dashboard-info"> 
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Additional info')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->_prepareLayout()['tenant_name']['value']) ?><br>
                    <?= $block->escapeHtml($block->_prepareLayout()['phone_number']['value']) ?><br>
                </p>
            </div>
        </div>
    </div>
</div>
